name = input("Whos first day st school is it")
print(f"It was {name} first day at school")
print(f"And she was super excited for lunch")
print(f"And spaghetti was super excited for lunch")
print("He had a sandwich and a bannana")
