name = input("Whos first day st school is it")
print(f"It was {name} first day at school")
print(f"And jake was super excited for lunch")
print("He had a sandwich and a bannana")
print("He was so excited he ate his lunch in 5 minutes")
