name = input("Who's first day st school is it")
print(f"It was {name} first day at school")
print(f"And she was super excited for lunch")
print(f"And jake was super excited for lunch")
print("He had a sandwich and a banana")
print("He was so excited he was drooling")
print("But his lunch got stolen")
name = input("who stole Jake's lunch")
name = input("Who did Jake chase across the cafeteria")
print(f"Jake chased {name} across the cafeteria")
print(f"After twenty minutes, Jake was able to trip Michelle")
print(f"Michelle ended up apologizing and returning the lunch")